security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

#security:
#    providers:
#        in_memory:
#            memory:
#                users:
###                    user:
###                        password: user
###                        roles: 'ROLE_USER'
#                    admin1:
#                        password: 0000
#                        roles: 'ROLE_ADMIN'
#        our_db_provider:
#            entity:
#                class: AppBundle:User
#
#        webservice:
#            id: AppBundle\Security\User\WebserviceUserProvider
#
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        AppBundle\Security\User\WebserviceUser:
#            algorithm: bcrypt
#            cost: 12
#        AppBundle\Entity\User:
#            algorithm: bcrypt
#
#    firewalls:
#        main:
#            anonymous: ~
#            pattern:    ^/
#            http_basic: ~
#            provider: our_db_provider
#            form_login:
#                login_path: /login
#                check_path: /login
#
#        secured_area:
#            pattern: ^/
#            anonymous: ~
#            logout:
#                path:   /logout
#                target: /
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#
##
##    access_control:
##        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
##        - { path: ^/, roles: ROLE_ADMIN }
#
#
