# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

        our_db_provider:
                    entity:
                        class: AppBundle:User
                        property: username

        webservice:
            id: AppBundle\Security\User\WebserviceUserProvider

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Security\User\WebserviceUser:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        main:
            pattern:    ^/login/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
            our_db_provider:
                entity:
                    class: AppBundle:User
                    property: username

